msaconfig:
  ipaddress: "192.168.10.1"
  dbtype: "oracle"
---
spring:
  profiles: local

msaconfig:
  ipaddress: "192.168.10.4"
  dbtype: "mysql"
---
spring:
  profiles: dev

msaconfig:
  ipaddress: "192.168.10.3"
  dbtype: "nosql"
---
